const chars = [
    {char: "a",code:null},
    {char: "ɛ",code:"&#603",key: "e"},
    {char: "i",code:null},
    {char: "ɔ",code:"&#596",key: "o"},
    {char: "u",code:null},
    
    {char: "b",code:null},
    {char: "ʦ",code:"&#678",key: "c"},
    {char: "d",code:null},
    {char: "x",code:"&#120"},
    {char: "f",code:null},
    {char: "g",code:null},
    {char: "j",code:null},
    {char: "k",code:null},
    {char: "l",code:null},
    {char: "m",code:null},
    {char: "n",code:null},
    {char: "ŋ",code:"&#331",key: "N"},
    {char: "ɲ",code:"&#626",key: "$N"},
    {char: "p",code:null},
    {char: "r",code:null},
    {char: "s",code:null},
    {char: "ʃ",code:"&#643",key: "S"},
    {char: "t",code:null},
    {char: "w",code:null},
    {char: "v",code:null},
    {char: "z",code:null},
    {char: "ˈ",code:"&#712",key:"'",button:false},
    {char: " ",code:null,key:" ",button:false},
]